// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: api/logsearch/v1/logsearch.proto

package logsearchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeywordMode int32

const (
	KeywordMode_KEYWORD_MODE_UNSPECIFIED KeywordMode = 0
	KeywordMode_KEYWORD_MODE_ALL         KeywordMode = 1
	KeywordMode_KEYWORD_MODE_ANY         KeywordMode = 2
)

// Enum value maps for KeywordMode.
var (
	KeywordMode_name = map[int32]string{
		0: "KEYWORD_MODE_UNSPECIFIED",
		1: "KEYWORD_MODE_ALL",
		2: "KEYWORD_MODE_ANY",
	}
	KeywordMode_value = map[string]int32{
		"KEYWORD_MODE_UNSPECIFIED": 0,
		"KEYWORD_MODE_ALL":         1,
		"KEYWORD_MODE_ANY":         2,
	}
)

func (x KeywordMode) Enum() *KeywordMode {
	p := new(KeywordMode)
	*p = x
	return p
}

func (x KeywordMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeywordMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_logsearch_v1_logsearch_proto_enumTypes[0].Descriptor()
}

func (KeywordMode) Type() protoreflect.EnumType {
	return &file_api_logsearch_v1_logsearch_proto_enumTypes[0]
}

func (x KeywordMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeywordMode.Descriptor instead.
func (KeywordMode) EnumDescriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type ListLogFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Pods          []string               `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	Containers    []string               `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	FilePatterns  []string               `protobuf:"bytes,4,rep,name=file_patterns,json=filePatterns,proto3" json:"file_patterns,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogFilesRequest) Reset() {
	*x = ListLogFilesRequest{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogFilesRequest) ProtoMessage() {}

func (x *ListLogFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogFilesRequest.ProtoReflect.Descriptor instead.
func (*ListLogFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{2}
}

func (x *ListLogFilesRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ListLogFilesRequest) GetPods() []string {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *ListLogFilesRequest) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *ListLogFilesRequest) GetFilePatterns() []string {
	if x != nil {
		return x.FilePatterns
	}
	return nil
}

func (x *ListLogFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt    string                 `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	SourceType    string                 `protobuf:"bytes,7,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceRule    string                 `protobuf:"bytes,8,opt,name=source_rule,json=sourceRule,proto3" json:"source_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFile) Reset() {
	*x = LogFile{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFile) ProtoMessage() {}

func (x *LogFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFile.ProtoReflect.Descriptor instead.
func (*LogFile) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{3}
}

func (x *LogFile) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogFile) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogFile) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LogFile) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *LogFile) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LogFile) GetSourceRule() string {
	if x != nil {
		return x.SourceRule
	}
	return ""
}

type ListLogFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*LogFile             `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogFilesResponse) Reset() {
	*x = ListLogFilesResponse{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogFilesResponse) ProtoMessage() {}

func (x *ListLogFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogFilesResponse.ProtoReflect.Descriptor instead.
func (*ListLogFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{4}
}

func (x *ListLogFilesResponse) GetFiles() []*LogFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListLogFilesResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Keywords       []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	KeywordMode    KeywordMode            `protobuf:"varint,2,opt,name=keyword_mode,json=keywordMode,proto3,enum=logsearch.v1.KeywordMode" json:"keyword_mode,omitempty"`
	CaseSensitive  bool                   `protobuf:"varint,3,opt,name=case_sensitive,json=caseSensitive,proto3" json:"case_sensitive,omitempty"`
	Namespaces     []string               `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Pods           []string               `protobuf:"bytes,5,rep,name=pods,proto3" json:"pods,omitempty"`
	Containers     []string               `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	FilePatterns   []string               `protobuf:"bytes,7,rep,name=file_patterns,json=filePatterns,proto3" json:"file_patterns,omitempty"`
	BeforeContext  int32                  `protobuf:"varint,8,opt,name=before_context,json=beforeContext,proto3" json:"before_context,omitempty"`
	AfterContext   int32                  `protobuf:"varint,9,opt,name=after_context,json=afterContext,proto3" json:"after_context,omitempty"`
	MaxResults     int32                  `protobuf:"varint,10,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	MaxBytes       int64                  `protobuf:"varint,11,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,12,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	StartTime      string                 `protobuf:"bytes,13,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        string                 `protobuf:"bytes,14,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchRequest) GetKeywordMode() KeywordMode {
	if x != nil {
		return x.KeywordMode
	}
	return KeywordMode_KEYWORD_MODE_UNSPECIFIED
}

func (x *SearchRequest) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

func (x *SearchRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *SearchRequest) GetPods() []string {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *SearchRequest) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *SearchRequest) GetFilePatterns() []string {
	if x != nil {
		return x.FilePatterns
	}
	return nil
}

func (x *SearchRequest) GetBeforeContext() int32 {
	if x != nil {
		return x.BeforeContext
	}
	return 0
}

func (x *SearchRequest) GetAfterContext() int32 {
	if x != nil {
		return x.AfterContext
	}
	return 0
}

func (x *SearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *SearchRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *SearchRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *SearchRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SearchRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type LogMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,3,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	File          string                 `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	LineNumber    int64                  `protobuf:"varint,6,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Text          string                 `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	Before        []string               `protobuf:"bytes,9,rep,name=before,proto3" json:"before,omitempty"`
	After         []string               `protobuf:"bytes,10,rep,name=after,proto3" json:"after,omitempty"`
	SourceType    string                 `protobuf:"bytes,11,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceRule    string                 `protobuf:"bytes,12,opt,name=source_rule,json=sourceRule,proto3" json:"source_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMatch) Reset() {
	*x = LogMatch{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMatch) ProtoMessage() {}

func (x *LogMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMatch.ProtoReflect.Descriptor instead.
func (*LogMatch) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{6}
}

func (x *LogMatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *LogMatch) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogMatch) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *LogMatch) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogMatch) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogMatch) GetLineNumber() int64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *LogMatch) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogMatch) GetBefore() []string {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *LogMatch) GetAfter() []string {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *LogMatch) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LogMatch) GetSourceRule() string {
	if x != nil {
		return x.SourceRule
	}
	return ""
}

type SearchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Matches          []*LogMatch            `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	ScannedFiles     int32                  `protobuf:"varint,2,opt,name=scanned_files,json=scannedFiles,proto3" json:"scanned_files,omitempty"`
	ScannedBytes     int64                  `protobuf:"varint,3,opt,name=scanned_bytes,json=scannedBytes,proto3" json:"scanned_bytes,omitempty"`
	Truncated        bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	TruncationReason string                 `protobuf:"bytes,5,opt,name=truncation_reason,json=truncationReason,proto3" json:"truncation_reason,omitempty"`
	ElapsedMs        int64                  `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logsearch_v1_logsearch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_logsearch_v1_logsearch_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetMatches() []*LogMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *SearchResponse) GetScannedFiles() int32 {
	if x != nil {
		return x.ScannedFiles
	}
	return 0
}

func (x *SearchResponse) GetScannedBytes() int64 {
	if x != nil {
		return x.ScannedBytes
	}
	return 0
}

func (x *SearchResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *SearchResponse) GetTruncationReason() string {
	if x != nil {
		return x.TruncationReason
	}
	return ""
}

func (x *SearchResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

var File_api_logsearch_v1_logsearch_proto protoreflect.FileDescriptor

const file_api_logsearch_v1_logsearch_proto_rawDesc = "" +
	"\n" +
	" api/logsearch/v1/logsearch.proto\x12\flogsearch.v1\"\x0f\n" +
	"\rHealthRequest\"E\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"\xa4\x01\n" +
	"\x13ListLogFilesRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12\x12\n" +
	"\x04pods\x18\x02 \x03(\tR\x04pods\x12\x1e\n" +
	"\n" +
	"containers\x18\x03 \x03(\tR\n" +
	"containers\x12#\n" +
	"\rfile_patterns\x18\x04 \x03(\tR\ffilePatterns\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xe2\x01\n" +
	"\aLogFile\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x06 \x01(\tR\n" +
	"modifiedAt\x12\x1f\n" +
	"\vsource_type\x18\a \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\vsource_rule\x18\b \x01(\tR\n" +
	"sourceRule\"a\n" +
	"\x14ListLogFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.logsearch.v1.LogFileR\x05files\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"\xf6\x03\n" +
	"\rSearchRequest\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\x12<\n" +
	"\fkeyword_mode\x18\x02 \x01(\x0e2\x19.logsearch.v1.KeywordModeR\vkeywordMode\x12%\n" +
	"\x0ecase_sensitive\x18\x03 \x01(\bR\rcaseSensitive\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\tR\n" +
	"namespaces\x12\x12\n" +
	"\x04pods\x18\x05 \x03(\tR\x04pods\x12\x1e\n" +
	"\n" +
	"containers\x18\x06 \x03(\tR\n" +
	"containers\x12#\n" +
	"\rfile_patterns\x18\a \x03(\tR\ffilePatterns\x12%\n" +
	"\x0ebefore_context\x18\b \x01(\x05R\rbeforeContext\x12#\n" +
	"\rafter_context\x18\t \x01(\x05R\fafterContext\x12\x1f\n" +
	"\vmax_results\x18\n" +
	" \x01(\x05R\n" +
	"maxResults\x12\x1b\n" +
	"\tmax_bytes\x18\v \x01(\x03R\bmaxBytes\x12'\n" +
	"\x0ftimeout_seconds\x18\f \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"start_time\x18\r \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x0e \x01(\tR\aendTime\"\xcc\x02\n" +
	"\bLogMatch\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x03 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x12\n" +
	"\x04file\x18\x05 \x01(\tR\x04file\x12\x1f\n" +
	"\vline_number\x18\x06 \x01(\x03R\n" +
	"lineNumber\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04text\x18\b \x01(\tR\x04text\x12\x16\n" +
	"\x06before\x18\t \x03(\tR\x06before\x12\x14\n" +
	"\x05after\x18\n" +
	" \x03(\tR\x05after\x12\x1f\n" +
	"\vsource_type\x18\v \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\vsource_rule\x18\f \x01(\tR\n" +
	"sourceRule\"\xf6\x01\n" +
	"\x0eSearchResponse\x120\n" +
	"\amatches\x18\x01 \x03(\v2\x16.logsearch.v1.LogMatchR\amatches\x12#\n" +
	"\rscanned_files\x18\x02 \x01(\x05R\fscannedFiles\x12#\n" +
	"\rscanned_bytes\x18\x03 \x01(\x03R\fscannedBytes\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\x12+\n" +
	"\x11truncation_reason\x18\x05 \x01(\tR\x10truncationReason\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x06 \x01(\x03R\telapsedMs*W\n" +
	"\vKeywordMode\x12\x1c\n" +
	"\x18KEYWORD_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KEYWORD_MODE_ALL\x10\x01\x12\x14\n" +
	"\x10KEYWORD_MODE_ANY\x10\x022\xf3\x01\n" +
	"\x10LogSearchService\x12C\n" +
	"\x06Health\x12\x1b.logsearch.v1.HealthRequest\x1a\x1c.logsearch.v1.HealthResponse\x12U\n" +
	"\fListLogFiles\x12!.logsearch.v1.ListLogFilesRequest\x1a\".logsearch.v1.ListLogFilesResponse\x12C\n" +
	"\x06Search\x12\x1b.logsearch.v1.SearchRequest\x1a\x1c.logsearch.v1.SearchResponseB(Z&logsearch/api/logsearch/v1;logsearchv1b\x06proto3"

var (
	file_api_logsearch_v1_logsearch_proto_rawDescOnce sync.Once
	file_api_logsearch_v1_logsearch_proto_rawDescData []byte
)

func file_api_logsearch_v1_logsearch_proto_rawDescGZIP() []byte {
	file_api_logsearch_v1_logsearch_proto_rawDescOnce.Do(func() {
		file_api_logsearch_v1_logsearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_logsearch_v1_logsearch_proto_rawDesc), len(file_api_logsearch_v1_logsearch_proto_rawDesc)))
	})
	return file_api_logsearch_v1_logsearch_proto_rawDescData
}

var file_api_logsearch_v1_logsearch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_logsearch_v1_logsearch_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_logsearch_v1_logsearch_proto_goTypes = []any{
	(KeywordMode)(0),             // 0: logsearch.v1.KeywordMode
	(*HealthRequest)(nil),        // 1: logsearch.v1.HealthRequest
	(*HealthResponse)(nil),       // 2: logsearch.v1.HealthResponse
	(*ListLogFilesRequest)(nil),  // 3: logsearch.v1.ListLogFilesRequest
	(*LogFile)(nil),              // 4: logsearch.v1.LogFile
	(*ListLogFilesResponse)(nil), // 5: logsearch.v1.ListLogFilesResponse
	(*SearchRequest)(nil),        // 6: logsearch.v1.SearchRequest
	(*LogMatch)(nil),             // 7: logsearch.v1.LogMatch
	(*SearchResponse)(nil),       // 8: logsearch.v1.SearchResponse
}
var file_api_logsearch_v1_logsearch_proto_depIdxs = []int32{
	4, // 0: logsearch.v1.ListLogFilesResponse.files:type_name -> logsearch.v1.LogFile
	0, // 1: logsearch.v1.SearchRequest.keyword_mode:type_name -> logsearch.v1.KeywordMode
	7, // 2: logsearch.v1.SearchResponse.matches:type_name -> logsearch.v1.LogMatch
	1, // 3: logsearch.v1.LogSearchService.Health:input_type -> logsearch.v1.HealthRequest
	3, // 4: logsearch.v1.LogSearchService.ListLogFiles:input_type -> logsearch.v1.ListLogFilesRequest
	6, // 5: logsearch.v1.LogSearchService.Search:input_type -> logsearch.v1.SearchRequest
	2, // 6: logsearch.v1.LogSearchService.Health:output_type -> logsearch.v1.HealthResponse
	5, // 7: logsearch.v1.LogSearchService.ListLogFiles:output_type -> logsearch.v1.ListLogFilesResponse
	8, // 8: logsearch.v1.LogSearchService.Search:output_type -> logsearch.v1.SearchResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_logsearch_v1_logsearch_proto_init() }
func file_api_logsearch_v1_logsearch_proto_init() {
	if File_api_logsearch_v1_logsearch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_logsearch_v1_logsearch_proto_rawDesc), len(file_api_logsearch_v1_logsearch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_logsearch_v1_logsearch_proto_goTypes,
		DependencyIndexes: file_api_logsearch_v1_logsearch_proto_depIdxs,
		EnumInfos:         file_api_logsearch_v1_logsearch_proto_enumTypes,
		MessageInfos:      file_api_logsearch_v1_logsearch_proto_msgTypes,
	}.Build()
	File_api_logsearch_v1_logsearch_proto = out.File
	file_api_logsearch_v1_logsearch_proto_goTypes = nil
	file_api_logsearch_v1_logsearch_proto_depIdxs = nil
}
