// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/logsearch/v1/logsearch.proto

package logsearchv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "logsearch/api/logsearch/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LogSearchServiceName is the fully-qualified name of the LogSearchService service.
	LogSearchServiceName = "logsearch.v1.LogSearchService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LogSearchServiceHealthProcedure is the fully-qualified name of the LogSearchService's Health RPC.
	LogSearchServiceHealthProcedure = "/logsearch.v1.LogSearchService/Health"
	// LogSearchServiceListLogFilesProcedure is the fully-qualified name of the LogSearchService's
	// ListLogFiles RPC.
	LogSearchServiceListLogFilesProcedure = "/logsearch.v1.LogSearchService/ListLogFiles"
	// LogSearchServiceSearchProcedure is the fully-qualified name of the LogSearchService's Search RPC.
	LogSearchServiceSearchProcedure = "/logsearch.v1.LogSearchService/Search"
)

// LogSearchServiceClient is a client for the logsearch.v1.LogSearchService service.
type LogSearchServiceClient interface {
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
	ListLogFiles(context.Context, *connect.Request[v1.ListLogFilesRequest]) (*connect.Response[v1.ListLogFilesResponse], error)
	Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error)
}

// NewLogSearchServiceClient constructs a client for the logsearch.v1.LogSearchService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLogSearchServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LogSearchServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	logSearchServiceMethods := v1.File_api_logsearch_v1_logsearch_proto.Services().ByName("LogSearchService").Methods()
	return &logSearchServiceClient{
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+LogSearchServiceHealthProcedure,
			connect.WithSchema(logSearchServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		listLogFiles: connect.NewClient[v1.ListLogFilesRequest, v1.ListLogFilesResponse](
			httpClient,
			baseURL+LogSearchServiceListLogFilesProcedure,
			connect.WithSchema(logSearchServiceMethods.ByName("ListLogFiles")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[v1.SearchRequest, v1.SearchResponse](
			httpClient,
			baseURL+LogSearchServiceSearchProcedure,
			connect.WithSchema(logSearchServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
	}
}

// logSearchServiceClient implements LogSearchServiceClient.
type logSearchServiceClient struct {
	health       *connect.Client[v1.HealthRequest, v1.HealthResponse]
	listLogFiles *connect.Client[v1.ListLogFilesRequest, v1.ListLogFilesResponse]
	search       *connect.Client[v1.SearchRequest, v1.SearchResponse]
}

// Health calls logsearch.v1.LogSearchService.Health.
func (c *logSearchServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListLogFiles calls logsearch.v1.LogSearchService.ListLogFiles.
func (c *logSearchServiceClient) ListLogFiles(ctx context.Context, req *connect.Request[v1.ListLogFilesRequest]) (*connect.Response[v1.ListLogFilesResponse], error) {
	return c.listLogFiles.CallUnary(ctx, req)
}

// Search calls logsearch.v1.LogSearchService.Search.
func (c *logSearchServiceClient) Search(ctx context.Context, req *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// LogSearchServiceHandler is an implementation of the logsearch.v1.LogSearchService service.
type LogSearchServiceHandler interface {
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
	ListLogFiles(context.Context, *connect.Request[v1.ListLogFilesRequest]) (*connect.Response[v1.ListLogFilesResponse], error)
	Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error)
}

// NewLogSearchServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLogSearchServiceHandler(svc LogSearchServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	logSearchServiceMethods := v1.File_api_logsearch_v1_logsearch_proto.Services().ByName("LogSearchService").Methods()
	logSearchServiceHealthHandler := connect.NewUnaryHandler(
		LogSearchServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(logSearchServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	logSearchServiceListLogFilesHandler := connect.NewUnaryHandler(
		LogSearchServiceListLogFilesProcedure,
		svc.ListLogFiles,
		connect.WithSchema(logSearchServiceMethods.ByName("ListLogFiles")),
		connect.WithHandlerOptions(opts...),
	)
	logSearchServiceSearchHandler := connect.NewUnaryHandler(
		LogSearchServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(logSearchServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	return "/logsearch.v1.LogSearchService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LogSearchServiceHealthProcedure:
			logSearchServiceHealthHandler.ServeHTTP(w, r)
		case LogSearchServiceListLogFilesProcedure:
			logSearchServiceListLogFilesHandler.ServeHTTP(w, r)
		case LogSearchServiceSearchProcedure:
			logSearchServiceSearchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLogSearchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLogSearchServiceHandler struct{}

func (UnimplementedLogSearchServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("logsearch.v1.LogSearchService.Health is not implemented"))
}

func (UnimplementedLogSearchServiceHandler) ListLogFiles(context.Context, *connect.Request[v1.ListLogFilesRequest]) (*connect.Response[v1.ListLogFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("logsearch.v1.LogSearchService.ListLogFiles is not implemented"))
}

func (UnimplementedLogSearchServiceHandler) Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("logsearch.v1.LogSearchService.Search is not implemented"))
}
